theme: jekyll-theme-cayman
title: Aadhaar API for .NET
description: A client library that provides an easy way to interact with the UIDAI Aadhaar services.
google_analytics: UA-98175937-1
google_site_verification: G-QWDiRJdyEmmTaWI1BKVOFYGTbXUQ6inOFotmn4H60
nuget_url: https://www.nuget.org/packages/Uidai.Aadhaar
uidai_url: https://authportal.uidai.gov.in/web/uidai/developer